;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-destructure-keys
        easy-kill
        helm-M-x
        hydra-cljr-code-menu/cljr-introduce-let
        paredit-close-square
        paredit-open-round
        ))

(setq mc/cmds-to-run-once
      '(
        crux-move-beginning-of-line
        describe-key
        hydra-cljr-code-menu/cljr-move-to-let
        hydra-cljr-code-menu/cljr-remove-let
        paredit-kill
        paredit-newline
        paredit-open-square
        ))
